import Key from '@/enums/Key';

export const modifierKeys = [
    Key.AltLeft,
    Key.AltRight,
    Key.ControlLeft,
    Key.ControlRight,
    Key.ShiftLeft,
    Key.ShiftRight,
] as const;

export const modifierKeyGroups = {
    Alt: [Key.AltLeft, Key.AltRight],
    Shift: [Key.ShiftLeft, Key.ShiftRight],
    Control: [Key.ControlLeft, Key.ControlRight],
} as const;

export const primaryKeys = [
    Key.ArrowDown,
    Key.ArrowLeft,
    Key.ArrowRight,
    Key.ArrowUp,
    Key.Backquote,
    Key.Backslash,
    Key.Backspace,
    Key.BracketLeft,
    Key.BracketRight,
    Key.CapsLock,
    Key.Comma,
    Key.Delete,
    Key.Digit0,
    Key.Digit1,
    Key.Digit2,
    Key.Digit3,
    Key.Digit4,
    Key.Digit5,
    Key.Digit6,
    Key.Digit7,
    Key.Digit8,
    Key.Digit9,
    Key.Minus,
    Key.Equal,
    Key.End,
    Key.Enter,
    Key.Escape,
    Key.Home,
    Key.Insert,
    Key.IntlBackslash,
    Key.IntlRo,
    Key.IntlYen,
    Key.F1,
    Key.F2,
    Key.F3,
    Key.F4,
    Key.F5,
    Key.F6,
    Key.F7,
    Key.F8,
    Key.F9,
    Key.F10,
    Key.F11,
    Key.F12,
    Key.F13,
    Key.F14,
    Key.F15,
    Key.F16,
    Key.F17,
    Key.F18,
    Key.F19,
    Key.F20,
    Key.F21,
    Key.F22,
    Key.F23,
    Key.F24,
    Key.KeyA,
    Key.KeyB,
    Key.KeyC,
    Key.KeyD,
    Key.KeyE,
    Key.KeyF,
    Key.KeyG,
    Key.KeyH,
    Key.KeyI,
    Key.KeyJ,
    Key.KeyK,
    Key.KeyL,
    Key.KeyM,
    Key.KeyN,
    Key.KeyO,
    Key.KeyP,
    Key.KeyQ,
    Key.KeyR,
    Key.KeyS,
    Key.KeyT,
    Key.KeyU,
    Key.KeyV,
    Key.KeyW,
    Key.KeyX,
    Key.KeyY,
    Key.KeyZ,
    Key.Numpad0,
    Key.Numpad1,
    Key.Numpad2,
    Key.Numpad3,
    Key.Numpad4,
    Key.Numpad5,
    Key.Numpad6,
    Key.Numpad7,
    Key.Numpad8,
    Key.Numpad9,
    Key.NumpadAdd,
    Key.NumpadSubtract,
    Key.NumpadMultiply,
    Key.NumpadDivide,
    Key.NumpadEqual,
    Key.NumpadDecimal,
    Key.NumpadComma,
    Key.NumpadEnter,
    Key.PageUp,
    Key.PageDown,
    Key.Pause,
    Key.Period,
    Key.Quote,
    Key.ScrollLock,
    Key.Semicolon,
    Key.Slash,
    Key.Space,
    Key.Tab,
] as const;

export const keyCodeToKeyName = {
    [Key.Alt]: 'Alt',
    [Key.AltLeft]: 'AltLeft',
    [Key.AltRight]: 'AltRight',
    [Key.ArrowDown]: 'ArrowDown',
    [Key.ArrowLeft]: 'ArrowLeft',
    [Key.ArrowRight]: 'ArrowRight',
    [Key.ArrowUp]: 'ArrowUp',
    [Key.Backquote]: '`',
    [Key.Backslash]: '\\',
    [Key.Backspace]: 'Backspace',
    [Key.BracketLeft]: '[',
    [Key.BracketRight]: ']',
    [Key.CapsLock]: 'CapsLock',
    [Key.Comma]: ',',
    [Key.Control]: 'Ctrl',
    [Key.ControlLeft]: 'ControlLeft',
    [Key.ControlRight]: 'ControlRight',
    [Key.Delete]: 'Delete',
    [Key.Digit0]: '0',
    [Key.Digit1]: '1',
    [Key.Digit2]: '2',
    [Key.Digit3]: '3',
    [Key.Digit4]: '4',
    [Key.Digit5]: '5',
    [Key.Digit6]: '6',
    [Key.Digit7]: '7',
    [Key.Digit8]: '8',
    [Key.Digit9]: '9',
    [Key.Minus]: '-',
    [Key.Equal]: '=',
    [Key.End]: 'End',
    [Key.Enter]: 'Enter',
    [Key.Escape]: 'Escape',
    [Key.Home]: 'Home',
    [Key.Insert]: 'Insert',
    [Key.IntlBackslash]: 'IntlBackslash',
    [Key.IntlRo]: 'IntlRo',
    [Key.IntlYen]: 'IntlYen',
    [Key.F1]: 'F1',
    [Key.F2]: 'F2',
    [Key.F3]: 'F3',
    [Key.F4]: 'F4',
    [Key.F5]: 'F5',
    [Key.F6]: 'F6',
    [Key.F7]: 'F7',
    [Key.F8]: 'F8',
    [Key.F9]: 'F9',
    [Key.F10]: 'F10',
    [Key.F11]: 'F11',
    [Key.F12]: 'F12',
    [Key.F13]: 'F13',
    [Key.F14]: 'F14',
    [Key.F15]: 'F15',
    [Key.F16]: 'F16',
    [Key.F17]: 'F17',
    [Key.F18]: 'F18',
    [Key.F19]: 'F19',
    [Key.F20]: 'F20',
    [Key.F21]: 'F21',
    [Key.F22]: 'F22',
    [Key.F23]: 'F23',
    [Key.F24]: 'F24',
    [Key.KeyA]: 'A',
    [Key.KeyB]: 'B',
    [Key.KeyC]: 'C',
    [Key.KeyD]: 'D',
    [Key.KeyE]: 'E',
    [Key.KeyF]: 'F',
    [Key.KeyG]: 'G',
    [Key.KeyH]: 'H',
    [Key.KeyI]: 'I',
    [Key.KeyJ]: 'J',
    [Key.KeyK]: 'K',
    [Key.KeyL]: 'L',
    [Key.KeyM]: 'M',
    [Key.KeyN]: 'N',
    [Key.KeyO]: 'O',
    [Key.KeyP]: 'P',
    [Key.KeyQ]: 'Q',
    [Key.KeyR]: 'R',
    [Key.KeyS]: 'S',
    [Key.KeyT]: 'T',
    [Key.KeyU]: 'U',
    [Key.KeyV]: 'V',
    [Key.KeyW]: 'W',
    [Key.KeyX]: 'X',
    [Key.KeyY]: 'Y',
    [Key.KeyZ]: 'Z',
    [Key.Numpad0]: 'Numpad 0',
    [Key.Numpad1]: 'Numpad 1',
    [Key.Numpad2]: 'Numpad 2',
    [Key.Numpad3]: 'Numpad 3',
    [Key.Numpad4]: 'Numpad 4',
    [Key.Numpad5]: 'Numpad 5',
    [Key.Numpad6]: 'Numpad 6',
    [Key.Numpad7]: 'Numpad 7',
    [Key.Numpad8]: 'Numpad 8',
    [Key.Numpad9]: 'Numpad 9',
    [Key.NumpadAdd]: '+',
    [Key.NumpadSubtract]: '-',
    [Key.NumpadMultiply]: '*',
    [Key.NumpadDivide]: '/',
    [Key.NumpadEqual]: '=',
    [Key.NumpadDecimal]: '.',
    [Key.NumpadComma]: ',',
    [Key.NumpadEnter]: 'Enter',
    [Key.PageUp]: 'PageUp',
    [Key.PageDown]: 'PageDown',
    [Key.Pause]: 'Pause',
    [Key.Period]: '.',
    [Key.Quote]: '"',
    [Key.ScrollLock]: 'ScrollLock',
    [Key.Semicolon]: ';',
    [Key.Shift]: 'Shift',
    [Key.ShiftLeft]: 'ShiftLeft',
    [Key.ShiftRight]: 'ShiftRight',
    [Key.Slash]: '/',
    [Key.Space]: 'Space',
    [Key.Tab]: 'Tab',
} as const;

export default {
    modifierKeys,
    modifierKeyGroups,
    primaryKeys,
    keyCodeToKeyName,
};
